grid_map_visualizations:

  - name: elevation_cloud
    type: point_cloud
    params:
     layer: elevation

  - name: sigma_cloud
    type: point_cloud
    params:
     layer: two_sigma_bound

  - name: map_region
    type: map_region
    params:
     color: 16777215
     line_width: 0.003

  - name: traversability_grid
    type: occupancy_grid
    params:
       layer: traversability
       data_min: 0.0
       data_max: 1.0

