arm:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50  

  # param# Position Controllers ---------------------------------------
  joint1_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: base_to_shoulder_joint
    pid: {p: 4, i: 0.3, d: 0.5}
  joint2_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: shoulder_to_arm_joint
    pid: {p: 4, i: 0.3, d: 0.5}
  joint3_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_to_yzwrist_joint
    pid: {p: 4, i: 0.3, d: 0.5}
  joint4_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: yzwrist_to_xywrist_joint
    pid: {p: 4, i: 0.3, d: 0.5}
  joint5_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: xywrist_to_xzwrist_joint
    pid: {p: 4, i: 0.3, d: 0.5}
  joint6_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: xzwrist_to_grip_joint
    pid: {p: 4, i: 0.3, d: 0.5}

    # type of controller before
    # type: effort_controllers/JointPositionController
