postprocessor_pipeline: # set by postprocessor_pipeline_name

  # Fill holes in the map with inpainting.
  - name: inpaint_variance
    type: gridMapCv/InpaintFilter
    params:
      input_layer: variance 
      output_layer: variance_inpainted
      radius: 0.05

  # Reduce noise with a radial blurring filter.
  - name: mean_in_radius_variance
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: variance_inpainted
      output_layer: variance_smooth
      radius: 0.06

  # Compute surface normals.
  - name: surface_normals_variance
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: variance_inpainted
      output_layers_prefix: variance_normal_vectors_
      radius: 0.2
      normal_vector_positive_axis: z

  # Add a color layer for visualization based on the surface normal.
  - name: normal_color_map_variance
    type: gridMapFilters/NormalColorMapFilter
    params:
      input_layers_prefix: variance_normal_vectors_
      output_layer: normal_color

  # Compute slope from surface normal.
  - name: slope_variance
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope_variance
      expression: acos(variance_normal_vectors_z)

  # Compute roughness as absolute difference from map to smoothened map.
  - name: roughness_variance
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: roughness_variance
      expression: abs(variance_inpainted - variance_smooth)

  # Compute traversability as normalized weighted sum of slope and roughness.
  - name: traversability_variance
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability_variance
      expression: 0.5 * (1.0 - (slope_variance / 0.6)) + 0.5 * (1.0 - (roughness_variance / 0.1))


  - name: risk
    type: gridMapFilters/CVaRFilter
    params:
      terrain_assessment_layer: traversability
      terrain_assessment_variance_layer: traversability_variance

      output_layer: risk



