ekf_localization:
    odom0: "/odometry/gps"
    odom0_config: [true, true, true,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    imu0: "/zed2/zed_node/imu/data"
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_remove_gravitational_acceleration: true
    publish_tf: false 
    two_d_mode: true      

    transform_time_offset: 0.1
