ekf_localization:
    frequency: 10
    sensor_timeout: 1
    two_d_mode: false
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "world"

    odom0: "/t265/odom/sample"
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, true,
                   false, false, false]

    imu0: "/imu/data"
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, true,
                  true, true, false]


