ekf_localization:
    odom0: "/odometry/gps"
    odom0_config: [true, true, true,
                   false, false, true,
                   false, false, false,
                   false, false, true,
                   false, false, false]

    imu0: "/t265/gyro/sample"
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  true, true, false]
    publish_tf: true
    two_d_mode: true      

 
