base_local_planner: "base_local_planner/TrajectoryPlannerROS"
base_global_planner: "navfn/NavfnROS"
TrajectoryPlannerROS:
   max_vel_x: 1.0
   min_vel_x: 0.0
   max_vel_theta: 0.5
   min_in_place_vel_theta: 0.2
   acc_lim_x: 5.0
   acc_lim_theta: 5.0
   holonomic_robot: false 
   controller_frequency: 10.0
   yaw_goal_tolerance: 6.2830 
   xy_goal_tolerance: 1.50 

   #recovery_behaviors: [
   #    { name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery },
   #    { name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
   #]
   #
   #conservative_clear: 
   #    reset_distance: 3.00
   #
   #aggressive_clear:
   #    reset_distance: 1.84
