TrajectoryPlannerROS:
   max_vel_x: 0.5
   min_vel_x: 0.1
   max_vel_theta: 1.0
   min_in_place_vel_theta: 0.5
   acc_lim_x: 2.5
   acc_lim_theta: 3.2
   holonomic_robot: false
   controller_frequency: 10.0
