base_local_planner: "base_local_planner/TrajectoryPlannerROS"
base_global_planner: "navfn/NavfnROS"
TrajectoryPlannerROS:
   max_vel_x: 1.0
   min_vel_x: 0.2
   max_vel_theta: 1.0
   min_in_place_vel_theta: 0.25
   acc_lim_x: 10.0
   acc_lim_theta: 10.0
   holonomic_robot: true 
   controller_frequency: 20.0
   yaw_goal_tolerance: 6.28
   xy_goal_tolerance: 1.00
   meter_scoring: true
   oscillation_reset_dist: 0.05
   goal_distance_bias: 0.8
   path_distance_bias: 0.6
   occdist_scale: 0.01
   heading_lookahead: 0.325
   dwa: true
   min_in_place_rotational_vel: 0.2

   sim_time: 3.5
   sim_granularity: 0.025
   vx_samples: 10
   vtheta_sample: 3
   vtheta_samples: 20

   escape_vel: -0.1
   min_in_place_rotational_vel: 0.15
