global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 1.0
   publish_frequency: 0.5
   static_map: true
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: true
   rolling_window: false
   map_topic: "/proj_map"
