local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   
   update_frequency: 10
   publish_frequency: 10
   transform_tolerance: 1.0

   static_map: false 
   rolling_window: true

   obstacle_range: 6.5
   
   controller_patience: 2.0

   recovery_behaviors: [
        { name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
        { name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
   ]

   conservative_clear:
        reset_distance: 0.00
   aggressive_clear:
        reset_distance: 0.00
   
   width: 10.0
   height: 10.0

   origin_x: -6.0
   origin_y: -6.0

   resolution: 0.1

   plugins:
           - { name: obstacles, type: "costmap_2d::VoxelLayer"}
           - { name: inflation, type: "costmap_2d::InflationLayer"}
   obstacles:
      observation_sources: point_cloud_sensor
   
      point_cloud_sensor: {
           data_type: PointCloud2,
           topic: /cloud_obstacles,
           marking: true,
           clearing: true,
           min_obstacle_height: -99999.0,
           max_obstacle_height: 6.0
      } 
   inflation:
           inflation_radius: 0.50
