local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   
   update_frequency: 10
   publish_frequency: 10
   transform_tolerance: 5.0

   static_map: false
   rolling_window: true
   
   width: 6.0
   height: 6.0
   resolution: 0.05
  
   plugins:
           - { name : obstacles, type: "costmap_2d::ObstacleLayer" }
   obstacles:
           observation_sources: point_cloud_sensor
           point_cloud_sensor: { sensor_frame: ZEDMini_optical_depth_frame, data_type: PointCloud2, topic: /cloud_obstacles, marking: true, clearing: true} 
           footprint_clearing_enabled: true

