local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   
   obstacle_range: 2.5
   raytrace_range: 3.0

   update_frequency: 2
   publish_frequency: 2
   #transform_tolerance: 5.0
   
   static_map: false
   rolling_window: true
  
   width: 8.0
   height: 8.0

   point_cloud_sensor: {
           sensor_frame: zed2_base_link,
           data_type: PointCloud2,
           topic: /cloud_obstacles,
           expected_update_rate: 0.5,
           marking: true,
           clearing: true,
           min_obstacle_height: -99999.0,
           max_obstacle_height: 99999.0
   }

inflation_radius: 0.55
