local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   
   update_frequency: 30
   publish_frequency: 10
   transform_tolerance: 5.0

   static_map: false 
   rolling_window: true

   map_topic: /grid_map 
   # plugins:
           # - {name: static_layer, type: "costmap_2d::StaticLayer"}
              # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

              # static_layer:
           # map_topic: /elevation_map_raw_visualization/traversability_grid 
         # subscribe_to_updates: true
         #inflation_layer:
           #inflation_radius: 0.1
            #         cost_scaling_factor: 6.0

